name: Run tests

on:
  pull_request:
    branches: [ "release/*", "main" ]
  push:
    branches: [ "release/*", "main" ]

jobs:
  odata-tests:
    uses: ./.github/workflows/odata-reusable-unit-test.yml
    with:
      java-version: '21'
      distribution: 'temurin'
      maven-options: '-PcheckFormat package'
    secrets: inherit

  rfc-tests:
    uses: ./.github/workflows/rfc-reusable-unit-test.yml
    with:
      java-version: '21'
      distribution: 'temurin'
      maven-options: '-PcheckFormat'
