name: build-and-publish
# - docker-image

on:
 workflow_call:
   inputs:
     final_version:
       required: true
       type: string

jobs:
  determine-connector-version:
    runs-on: ubuntu-latest
    outputs:
      CAMUNDA_VERSION: ${{ steps.connectors_repo_version.outputs.CAMUNDA_VERSION }}

    steps:
      - uses: actions/checkout@v5

      - name: set up jdk 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set connectors repo version in output
        id: connectors_repo_version
        run: echo "CAMUNDA_VERSION=$(mvn help:evaluate -Dexpression=version.camunda -q -DforceStdout)" >> "$GITHUB_OUTPUT"


  build-and-test:
    needs: determine-connector-version
    uses: ./.github/workflows/odata-reusable-build-and-test.yml
    with:
      java-version: '21'
      distribution: 'temurin'
      maven-options: '-PcheckFormat package'
    secrets: inherit

  gh_release:
    needs: [ build-and-test, determine-connector-version ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      # no need to build anything as all release-related artifacts (except the docker image) are under version control
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "element-templates/*.json,odata-connector/mtad.yaml.example"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "Odata ${{ inputs.final_version }}"
          name: "OData ${{ inputs.final_version }}"
          body: "OData Release ${{ inputs.final_version }}"
          allowUpdates: 'true'
          removeArtifacts: 'true'

  build-and-publish:
    needs: [build-and-test, determine-connector-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false # we rely on step outputs, no need for environment variables
          secrets: |
            secret/data/products/consulting/ci/common DOCKERHUB_USER;
            secret/data/products/consulting/ci/common DOCKERHUB_PASSWORD;

      - name: set up jdk 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set connector version
        run: |
          mvn versions:set -DnewVersion=${{ inputs.final_version }} -DgenerateBackupPoms=false
      - name: build
        run: mvn -B -PcheckFormat package --file pom.xml -DskipTests # as we've run the tests in the previous job

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ steps.secrets.outputs.DOCKERHUB_USER }}
          password: ${{ steps.secrets.outputs.DOCKERHUB_PASSWORD }}

      - name: sap-odata-connector - build and push docker image tag ${{ inputs.final_version }}
        uses: docker/build-push-action@v6
        with:
          context: odata-connector
          file: odata-connector/Dockerfile
          build-args: |
            CAMUNDA_CONNECTORS_VERSION=${{ needs.determine-connector-version.outputs.CAMUNDA_VERSION }}
          push: true
          tags: |
            camunda/sap-odata-connector${{ inputs.final_version }}
          #            camunda/sap-odata-connector:latest
          platforms: linux/amd64
          provenance: false

#  deploy-to-btp:
#    needs: build-and-publish
#    uses: ./.github/workflows/reusable-deploy.yml
#    with:
#      connector_version: ${{ needs.build-and-publish.outputs.VERSION }}
#      region: 'bru-2'
#      cf_api_endpoint: 'https://api.cf.eu10-004.hana.ondemand.com'
#      cf_org: camunda-dev
#      cf_space: sap-integration
#    secrets: inherit
