name: rfc-build-and-publish

on:
 workflow_call:
   inputs:
     final_version:
       required: true
       type: string

jobs:
  unit-test:
    uses: ./.github/workflows/rfc-reusable-unit-test.yml
    with:
      java-version: '21'
      distribution: 'temurin'
      maven-options: '-PcheckFormat'
    secrets: inherit


  build-and-gh_release:
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: set up jdk 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set connector version
        run: |
          mvn versions:set -DnewVersion=${{ inputs.final_version }} -DgenerateBackupPoms=false
      - name: build project
        run: mvn clean package

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "rfc-connector/target/*.war,element-templates/*.json,rfc-connector/mtad.yaml.example"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "RFC ${{ inputs.final_version }}"
          name: "RFC ${{ inputs.final_version }}"
          body: "RFC Release ${{ inputs.final_version }}"
          allowUpdates: 'true'
          removeArtifacts: 'true'
