name: rfc-e2e-test

on:
    pull_request:
        branches: [ "release/*", "main" ]
    push:
        branches: [ "release/*", "main" ]

jobs:
  determine-connector-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.scope_version.outputs.VERSION }}

    steps:
      - uses: actions/checkout@v6

      - name: set up jdk 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: extract release version
        id: extract_version
        # this extracts <version> from pom.xml into env.VERSION
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_ENV"

      - name: scope the version into an output
        id: scope_version
        run: echo "VERSION=${{ env.VERSION }}" >> "$GITHUB_OUTPUT"

  deploy-to-btp:
    needs: determine-connector-version
    uses: ./.github/workflows/rfc-reusable-deploy.yml
    with:
      connector_version: ${{ needs.determine-connector-version.outputs.VERSION }}
      cf_api_endpoint: 'https://api.cf.eu10-004.hana.ondemand.com'
      cf_org: camunda-dev
      cf_space: sap-integration
    secrets: inherit

  e2e:
    needs: deploy-to-btp
    uses: ./.github/workflows/rfc-reusable-e2e-test.yml
    with:
      java-version: '25'
      distribution: 'temurin'
      maven-options: ''
    secrets: inherit

  undeploy:
    needs: [ determine-connector-version, e2e, deploy-to-btp ]
    if: always()
    uses: ./.github/workflows/rfc-reusable-undeploy.yml
    with:
      connector_version: ${{ needs.determine-connector-version.outputs.VERSION }}
      deployment_name: ${{ needs.deploy-to-btp.outputs.deployment_name }}
      cf_api_endpoint: 'https://api.cf.eu10-004.hana.ondemand.com'
      cf_org: camunda-dev
      cf_space: sap-integration
      cluster_uuid: ${{ needs.deploy-to-btp.outputs.cluster_uuid }}
    secrets: inherit
